name: Generate RPI Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-rpi-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run pi-gen-action
        uses: usimd/pi-gen-action@v1.10.0
        with:
          image-name: ezui
          hostname: ezui
          username: ezui
          password: ezui
          compression: none
          disable-first-boot-user-rename: 1
          enable-ssh: 1
          keyboard-keymap: us
          locale: en_US.UTF-8
          pi-gen-version: arm64
          release: bookworm
          stage-list: stage0 stage1 stage2
          verbose-output: true
